Nome: Thiago Rodrigues Vieira RA:61811795

# Análise de Dados Exploratória do Titanic

![titanic](img/titanic_historical.jpg "Pintura do Titanic")

# 1. Introdução

O RMS Titanic foi um navio de passageiros britânico operado pela empresa *White Star Line* que afundou no Oceano Atlântico Norte nas primeiras horas da manhã de 15 de abril de 1912, depois de atingir um iceberg durante sua viagem inaugural de Southampton a Nova York. Dos 2.224 passageiros e tripulantes a bordo, mais de 1.500 morreram, tornando o naufrágio um dos desastres marítimos comerciais mais mortais da história moderna em tempos de paz.

Neste estudo iremos explorar um conjunto de dados baseado na lista de passageiros do Titanic editada por Michael A. Findlay, publicada originalmente em Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd, e expandida com a ajuda da comunidade da Internet. Os arquivos HTML originais foram obtidos por Philip Hind (1999) e o *dataset* descreve o status de sobrevivência de passageiros individuais no Titanic. Ele não contém informações para a tripulação, mas contém idades atuais e estimadas para quase 80% dos passageiros.

## 1.1. Objetivos

O objetivo deste estudo é realizar uma Análise Exploratória dos Dados (Exploratory Data Analysis - EDA) do conjunto de dados `titanic3`, adaptado pelo autor e disponível em [data/titanic3.csv](data/titanic.csv); a fim de caracterizar o perfil dos sobreviventes do fatídico naufrágio. Especificiamente serão respondidas as seguintes questões de pesquisa:

1. [Qual é o número de Sobreviventes?](#3.1.-Qual-é-o-número-de-Sobreviventes?)
2. [Homens ou mulheres tiveram mais chances de sobreviver?](#3.2.-Homens-ou-mulheres-tiveram-mais-chances-de-sobreviver?)
3. [Qual classe social teve mais sobreviventes?](#3.3.-Qual-classe-social-teve-mais-sobreviventes?)
4. [Qual faixa etária teve mais chances de sobreviver?](#3.4.-Qual-faixa-etária-teve-mais-chances-de-sobreviver?)

# 2. Metodologia

Nesta seção será apresentado todo o processo de preparação, organização e limpeza de dados feito no *dataset* que possui os seguintes dados:

| Coluna          | Descrição                                                                 |
|-----------------|---------------------------------------------------------------------------|
| id_passageiro   | Identficador único do passageiro.                                         |
| classe          | Classe social.                                                            |
| sobreviveu      | Sobrevivente? Sim (1), Não (0).                                           |
| nome            | Nome do passageiro.                                                       |
| sexo            | Masculino (male), Feminino (female).                                      |
| idade           | Idade do passageiro.                                                      |
| irmaos_conjuges | Número de irmãos e cônjuges a bordo.                                      |
| pais_filhos     | Número de pais e filhos a bordo.                                          |
| bilhete         | Número do bilhete                                                         |
| tarifa          | Preço da tarifa do passageiro.                                            |
| cabine          | Cabine.                                                                   |
| embarque        | Nome do porto de embarque: C = Cherbourg; Q = Queenstown; S = Southampton |
| bote            | Bote salva vidas.                                                         |
| corpo           | Número de identificação do corpo.                                         |
| destino         | Local de desembarque do passageiro.                                       |

## OBSERVAÇÕES

- `classe` é uma aproximação do status socioeconômico na época, onde: 1 = Classe Alta1; 2 = Classe Média e 3 = Classe Baixa;
- `idade` está representada em anos, porém, se a idade for menor que Um (1) ou caso tenha sido estimada, ela estará com casas decimais xx.5;
- `tarifa` está em Libras esterlinas (British Pounds - £) anteriores a 1970;
- `irmaos_conjuges` e `pais_filhos`: as variáveis de relação familiar de algumas relações foram ignoradas; a seguir estão as definições usadas:
    - **Irmão**: Irmão, irmã, meio-irmão ou meia-irmã do passageiro a bordo do Titanic;
    - **Cônjuge**: Marido ou esposa do passageiro a bordo do Titanic (amantes e noivos ignorados);
    - **Pai**: Mãe ou pai do passageiro a bordo do Titanic;
    - **Criança**: Filho, Filha, Enteado ou Enteada do Passageiro a bordo do Titanic;
    - Outros parentes excluídos deste estudo incluem primos, sobrinhos / sobrinhas, tias / tios e parentes;
    - Algumas crianças viajavam apenas com uma babá, portanto foi atribuído 0 para elas em pais_filhos; 
    - Alguns viajaram com amigos ou vizinhos muito próximos em uma vila, no entanto, as definições não apóiam essas relações.

## 2.1. Configuração do Ambiente

In [ ]:
import  numpy  as  np 
import  pandas  as  pd

## 2.2. Leitura dos Dados

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
dados=pd.read_csv('/content/drive/MyDrive/titanic3.csv')

## 2.3. Organização e Limpeza dos Dados

### 2.3.1. Visão Geral do Conjunto de Dados

In [ ]:
dados.head(10)

In [ ]:
dados.set_index('id_passageiro',inplace=True)

### 2.3.2 Remoção de Colunas
Remoção de colunas incompletas e/ou desnecessárias para a análise.

In [ ]:
dadosTratados=dados.drop(columns=['cabine','bote'])

### 2.3.3. Dados Ausentes

In [ ]:
dadosTratados.isnull().sum()

#### 2.3.3.1 Idades Ausentes
Para os dados ausentes da coluna `idade` será feita a substituição dos dados vazios pela média das idades na época.

In [ ]:
mediaIdade=dadosTratados['idade'].mean()
dadosTratados['idade'] = dadosTratados['idade'].fillna(mediaIdade)
dadosTratados.isnull().sum()
dadosTratados

#### 2.3.3.2 Tarifas Ausentes
Para os dados ausentes da coluna `tarifa`será feita a substituição dos dados vazios pela média de preço das tarifas na época.

In [ ]:
mediaTarifa=dadosTratados['tarifa'].mean()
dadosTratados['tarifa'] = dadosTratados['tarifa'].fillna(mediaIdade)

#### 2.3.3.3 Portos de Embarque Ausentes
Para os dados ausentes da coluna `embarque`será feita a remoção dos dados vazios.

In [ ]:
dadosTratados.dropna(subset=['embarque','destino'])

## 2.4. Mapeamento de Dados
Para melhorar a análise e interpretação dos dados os seguintes atributos serão modificados:

| Coluna    | Original     | Modificado                          |
|:----------|:-------------|:------------------------------------|
| Classe    | 1, 2, 3      | Alta, Média, Baixa                  |
| Sexo      | male, female | M, F                                |
| Embarque  | C, Q, S      | Cherbourg, Queenstown, Southampton  |

In [ ]:
#Classes
dadosTratados['classe'] = dadosTratados['classe'].replace(1, 'Alta')
dadosTratados['classe'] = dadosTratados['classe'].replace(2, 'Media')
dadosTratados['classe'] = dadosTratados['classe'].replace(3, 'Baixa')

#Sexo
dadosTratados['sexo'] = dadosTratados['sexo'].replace('male', 'm')
dadosTratados['sexo'] = dadosTratados['sexo'].replace('female', 'f')

#Embarque
dadosTratados['embarque'] = dadosTratados['embarque'].replace('C', 'Cherbourg')
dadosTratados['embarque'] = dadosTratados['embarque'].replace('Q', 'Queenstown')
dadosTratados['embarque'] = dadosTratados['embarque'].replace('S', 'Southampton')

## 2.5.  Feature Engineering

A engenharia de recursos (*Feature Engineering*) é o processo de usar o conhecimento do domínio para extrair recursos dos dados brutos. Neste estudo serão acrescentadas as seguintes colunas para enriquecer a análise de dados:

| Coluna         | Descrição                                                         |
|:---------------|:------------------------------------------------------------------|
| total_parentes | Número total de parentes a bordo: `irmaos_conjuges + pais_filhos` |
| faixa_etaria   | Intervalo de idades dos passageiros.                              |

### 2.5.1 Total de Parentes

In [ ]:
parentes = dadosTratados['irmaos_conjuges']+dadosTratados['pais_filhos']
dadosTratados = dadosTratados.assign(total_parentes=parentes)
dadosTratados.head()

### 2.5.2 Faixas Etárias

In [ ]:
linhas = dadosTratados['classe'].count()
idade = list(dadosTratados['idade'])
p=1;
for n in range(linhas):
 
    if idade[n] <= 17:
       idade[n]="Jovem"
    elif 17 < idade[n] <= 65:
        idade[n] = "Adulto"    
    else:
        idade[n] = "Idoso"

dadosTratados['idade']=idade
dadosTratados.head(100)

# 3. Análise dos Dados

## 3.1. Qual é o número de Sobreviventes?

In [ ]:
dadosS=dadosTratados.query('sobreviveu == 1')
print('Sobreviveram:') 
dadosS['sobreviveu'].sum()

Sobreviveram:

500

## 3.2. Homens ou mulheres tiveram mais chances de sobreviver?

In [ ]:
Linhas = dados['sexo'].count()
sexo = list(dadosTratados['sexo'])
homem=0;
mulher=0;
for n in range(Linhas): 
    if sexo[n] == "f":
     mulher=mulher+1
    else:
      homem=homem+1

print(mulher)
print(homem)

211
289

## 3.3. Qual classe social teve mais sobreviventes?

In [ ]:
linhas = dados['classe'].count()
classe = list( dados['classe'])
alta=0;
media=0;
baixa=0;
for n in range(linhas): 
    if classe[n] == "Alta":
     alta = alta+1
    elif classe[n] == "Media":
     media= media+1
    else:
      baixa=  baixa+1

print(alta)
print(media)
print(baixa)

200
119
181

## 3.4. Qual faixa etária teve mais chances de sobreviver?

In [ ]:
Jovem = dados.query('idade == "Jovem"').count()
Adulto = dados.query('idade == "Adulto"').count()
Idoso = dados.query('idade == "Idoso"').count()

Jovem = str(Jovem['idade']);
print("Jovens: " +Jovem)

Adulto = str(Adulto['idade']);
print("Adultos: " +Adulto)

Idoso = str(Idoso['idade']);
print("Idosos: " +Idoso)

Jovens: 81
Adultos: 417
Idosos: 2

# REFERÊNCIAS

- [Titanic: Machine Learning from Disaster](https://www.kaggle.com/c/titanic/data)
- [Encyclopedia Titanica](https://www.encyclopedia-titanica.org/)
- [Basic Feature Engineering with the Titanic Data](https://triangleinequality.wordpress.com/2013/09/08/basic-feature-engineering-with-the-titanic-data/)
- Hind, Philip.  "Encyclopedia Titanica."  Online.  Internet. n.p.  02 Aug 1999.